### ISSUE TITLE
add "as seen in clojure" data

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/api-docs-generator#15]
@joshhead had the idea to be able to see which symbols are clojurescript-specific and which ones are also available in clojure.

We can just use the `index-v*.clj` files in the [gh-pages clojure branch](https://github.com/clojure/clojure/tree/gh-pages), which contain the API for each version.

After converting some namespaces like below, we can add a `clojure-symbol` attribute for each cljs symbol to create a releveant bridge between the two.

- `cljs.core => clojure.core`
- `cljs.pprint => clojure.pprint`
- `cljs.repl => clojure.repl`

**Comment by joshhead** [comment]
Thanks for adding this! I think it would also be useful to see which symbols from Clojure are *not* available in ClojureScript.

**Comment by shaunlebron** [comment]
@joshhead you must have venn-vision... haha, good idea.  added #18
