### ISSUE TITLE
create a "not-in-cljs.edn" build

### ISSUE THREAD

**Issue by shaunlebron** [cljsinfo/api-docs-generator#18]
@joshhead suggests the ability to determine which clojure core functions are not available in cljs.  We won't be able to add a flag to cljsdocs since its existence precludes the possibility.  Will have to create a separate build.

**Comment by shaunlebron** [comment]
fixed https://github.com/cljsinfo/api-docs-generator/commit/5d4c2f9b715aeffa4e3cd6607d7b1822f9b27086

There is a `:clj-not-cljs` key in the new [autodocs.edn](https://github.com/cljsinfo/api-docs-generator/blob/docs/autodocs.edn)

we also create a plaintext [`not-in-cljs`](https://github.com/cljsinfo/api-docs-generator/blob/docs/not-in-cljs) file for readability

**Comment by joshhead** [comment]
Excited for this one.
